backend:
  name: github
  repo: dackalacbayo/Tatong_website # Path to your Github repository
  branch: master # Branch to update

media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: "faq"
    label: "FaQ"
    folder: "src/pages/faQ"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime",format: "LL"}
      - {label: "Question", name: "question", widget: "markdown"}
      - {label: "Answer", name: "answer", widget: "markdown"}
